### ISSUE TITLE
Split the options to resize icons and disable text

### ISSUE THREAD

**Issue by thecrazy** [gregolsky/chrome-app-launcher#27]
Would be nice to be able to specify a custom icon size.

**Comment by gregolsky** [comment]
Sure, thanks for your input. I will look into this. The idea with this was to make options as simple as possible, but I guess this may be too simple for some people.

**Comment by gregolsky** [comment]
Done!

![desctop screenshot](https://cloud.githubusercontent.com/assets/1541805/16570185/24b9eaf8-4241-11e6-8cba-2d00548de51a.png)
