### ISSUE TITLE
Loss of task bar launcher

### ISSUE THREAD

**Issue by RayVanDervort** [gregolsky/chrome-app-launcher#46]
My chrome browser starts with 10 or more default pages I use every day at work. To open the browser in a new window or clean window, I click on the google search icon app in the launcher to open a blank search page, and don't have to wait for my default 10 or so pages to load and click on another tab to open. If the only way to open the browser clean is to first open all 10, as will be the case if the task bar launcher is gone. This is far from desirable. My database has over 1200 website I use for research. I also occasionally need IE for some sites that won't work with chrome. Can we not always change everything weekly without a little impact study? such seems to be the way of the internet, and I don't need to spend all mhy time in recovery of changes to get back to functionality.

**Comment by gregolsky** [comment]
@RayVanDervort, first of all I am sorry that name of the repository mislead you. I am not Google and I did not retire the original Chrome app launcher. This repository is for the Chrome extension offering some of the functionality included in the original Google product and which may serve as an alternative to the original. You can give it a shot here, if  you want https://chrome.google.com/webstore/detail/apps-launcher/ijmgkhchjindcjamnckoiahagecjnkdc . If there's any particular feature you would like me to add to the extension please create another ticket. This one is going to be closed. Thanks!
