### ISSUE TITLE
Consider making App Version

### ISSUE THREAD

**Issue by brandoncomputer** [gregolsky/chrome-app-launcher#49]
The plugin is great, but it would be even better if there was an app version I could pin to my taskbar.

**Comment by gregolsky** [comment]
I've been working on one some time ago, but unfortunately do not have time to continue. Maybe some day :) Also you can't make a Chrome app like this due to API restrictions - Chrome apps simply do not have access to browser data - only extensions do.

**Comment by brandoncomputer** [comment]
Actually, I was able to pin this in both Linux and Windows based OS as an app! 

/opt/google/chrome/google-chrome --app="chrome-extension://ijmgkhchjindcjamnckoiahagecjnkdc/popup.html"

**Comment by gregolsky** [comment]
Oh. That's good for you. :)

Not sure if it's Chrome's bug or a feature. Need to try it myself. Perhaps
I should put info in README, since there's quite a lot of people asking for
this.

Thanks!

pon., 27.06.2016 o 03:26 użytkownik brandoncomputer <
notifications@github.com> napisał:

> Actually, I was able to pin this in both Linux and Windows based OS as an
> app!
>
> /opt/google/chrome/google-chrome
> --app="chrome-extension://ijmgkhchjindcjamnckoiahagecjnkdc/popup.html"
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/gregolsky/chrome-app-launcher/issues/49#issuecomment-228636569>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABeGrXczQdTSASLacpmnlcqXsn5iCW8bks5qPyapgaJpZM4I8Qte>
> .
>
-- 
Grzegorz Lachowski

**Comment by gregolsky** [comment]
@brandoncomputer Huh, this really works. :P Hack or not, I'm gonna add info on it in the *README* and perhaps provide some scripts to create this kind of shortcut. Thanks!
