### ISSUE TITLE
offline use

### ISSUE THREAD

**Issue by fpvflyby** [gregolsky/chrome-app-launcher#50]
how to download apps for offline use

**Comment by gregolsky** [comment]
I think it depends on the app. I am sorry but your question is out of scope
of the extension and its features. Please try asking around specific Google
groups and also present the exact use case you have issues with.

sob., 25.06.2016 o 18:23 użytkownik fpv flyby <notifications@github.com>
napisał:

> how to download apps for offline use
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/gregolsky/chrome-app-launcher/issues/50>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/ABeGraGARQQqCJgAnwxZf4N6a0iflZsUks5qPVX_gaJpZM4I-YJv>
> .
>
-- 
Grzegorz Lachowski
