### ISSUE TITLE
Multiple icon colors

### ISSUE THREAD

**Issue by kshitijpatil** [gregolsky/chrome-app-launcher#52]
Please add support for adding multiple colors to the icon

**Comment by gregolsky** [comment]
I am not sure what exactly do you mean. Would you like me to add option to choose color for every single square in the icon? If so, this probably won't happen.

**Comment by kshitijpatil** [comment]
i mean to make it look like the chrome app launcher

**Comment by gregolsky** [comment]
Unfortunately I won't be trying to mimic Google product and also I do not own any rights to use their icon, as one for my extension.
