### ISSUE TITLE
shortcut

### ISSUE THREAD

**Issue by Mohamedazam113** [gregolsky/chrome-app-launcher#53]
Hi there,
Hope you all doing well.
Thanks for the great app, I'm kinda new to chrome, I was using Mozilla, so please if you can help.
I couldn't create a shortcut for app launcher at all, searched it on google and I tried every single way there but it couldn't work, so please tell me how to do it, or it's canceled and I can't do it?

Kind regards to you all

**Comment by gregolsky** [comment]
Google App Launcher has been cancelled by Google and this repository holds
just an alternative for it. Unfortunately it is not possible yet to create
a shortcut on the desktop for it. Somebody was able to hack his way to get
it on the desktop. See
https://github.com/gregolsky/chrome-app-launcher/issues/49

Sob., 2.07.2016, 14:25 użytkownik Mohamedazam113 <notifications@github.com>
napisał:

> Hi there,
> Hope you all doing well.
> Thanks for the great app, I'm kinda new to chrome, I was using Mozilla, so
> please if you can help.
> I couldn't create a shortcut for app launcher at all, searched it on
> google and I tried every single way there but it couldn't work, so please
> tell me how to do it, or it's canceled and I can't do it?
>
> Kind regards to you all
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/gregolsky/chrome-app-launcher/issues/53>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/ABeGrQmU3vM2_Cp_OD1OZQ1ldcUzOhQlks5qRli5gaJpZM4JDqks>
> .
>
-- 
Grzegorz Lachowski

**Comment by Mohamedazam113** [comment]
Hi gregolsky,
I'm sorry, this is my first day on github, plus I'm totally ignorant about coding, so I didn't know what issue #49 suppose to lead me to but a conversation between you and brandoncomputer with no details about how to do it, further explanation would be great, if you can.
thanks again for your help

**Comment by gregolsky** [comment]
@Mohamedazam113 Are we talking Windows, Mac OS X or Linux?

Basically you need to run Chrome with an option `--app`:

```
/path/to/google-chrome --app="chrome-extension://ijmgkhchjindcjamnckoiahagecjnkdc/popup.html"
```

On Windows you could wrap it in an `lnk` shortcut file, while unix-like systems just need a simple `sh` script.

**Comment by Sumanarian** [comment]
@gregolsky 

Thank you SOOOO much for this!!
  I loved using the App launcher, and I even searched every where for it
when I had to re-install Chrome.
The previous fix that I found had been destroyed by the removal of
the App launcher from Google Servers.

![image](https://cloud.githubusercontent.com/assets/22341947/18736630/a101d082-803d-11e6-910f-479894f106bd.png)
