### ISSUE TITLE
improve icon spacing

### ISSUE THREAD

**Issue by kshitijpatil** [gregolsky/chrome-app-launcher#54]
Could you please improve the spacing between app icons (or provide settings to adjust it)?

**Comment by gregolsky** [comment]
Sure, please provide a screenshot and mark on it which space you're after.

śr., 6.07.2016 o 04:01 użytkownik Kshitij Patil <notifications@github.com>
napisał:

> Could you please improve the spacing between app icons (or provide
> settings to adjust it)?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/gregolsky/chrome-app-launcher/issues/54>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/ABeGrVHu9WfSKK9yrhAzv95zYniu2bvoks5qSwx6gaJpZM4JFsJT>
> .
>
-- 
Grzegorz Lachowski

**Comment by kshitijpatil** [comment]
This is an image with launcher width 300 and apps per row 3 settings. The icons look too big.

![capture](https://cloud.githubusercontent.com/assets/6806872/16624659/3b9f4860-43bf-11e6-865d-40ddf9af61de.PNG)

**Comment by gregolsky** [comment]
Oh I see what you mean now. I didn't notice since mine aren't that big. I
will look into it.

Śr., 6.07.2016, 17:51 użytkownik Kshitij Patil <notifications@github.com>
napisał:

> This is an image with launcher width 300 and apps per row 3 settings. The
> icons look too big.
>
> [image: capture]
> <https://cloud.githubusercontent.com/assets/6806872/16624659/3b9f4860-43bf-11e6-865d-40ddf9af61de.PNG>
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/gregolsky/chrome-app-launcher/issues/54#issuecomment-230815483>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABeGrSVN-CXSJw6MpYycH3FfLKtz-kiGks5qS88DgaJpZM4JFsJT>
> .
>
-- 
Grzegorz Lachowski

**Comment by gregolsky** [comment]
The padding option is finished, I'll test and release it tomorrow, however it's actually the problem of the icons we're workarounding here (various padding inside the icon between apps) and even if it looks better with a bit of padding, it's probably the author of the app, who should have fix it in the first place. Oh well.. Nevertheless 5px padding looks nice, however I made it the way you can go up to crazy 20px padding if you want. Releasing the fix tomorrow.
