### ISSUE TITLE
Open new window

### ISSUE THREAD

**Issue by everterra** [gregolsky/chrome-app-launcher#66]
I would like to open a new window for Gmail (sometimes other apps). Chrome shortcuts to open new window don´t work.

The ideal thing for Gmail it would be a pop up window. Frequently I need to see other pages when I´m composing an email.

Thanks.

**Comment by TerenceH** [comment]
@everterra , on the [Chrome Apps page](chrome://apps/), right click on any icon, select the "open as window" menu item (screenshot below). Now, when you click on an icon in the App Launcher, the app will open as a separate window. 
![chrome apps open in new window](https://user-images.githubusercontent.com/12010132/31856900-e8085e12-b6a4-11e7-8826-e9198b743fe8.JPG)

**Comment by gregolsky** [comment]
@TerenceH is right. Thanks!
