### ISSUE TITLE
Can´t find Chrome Web Store app

### ISSUE THREAD

**Issue by everterra** [gregolsky/chrome-app-launcher#67]
I have Chrome Web Store app instaled and I can´t find it.

I seet it in the tab chrome://apps/

And in the Chrome Web Store can´t find the app to install...

**Comment by gregolsky** [comment]
Yeah, webstore app is built-in. API doesn't return built-in apps, so I'm not sure how to tackle that.
We might hard-code some built-in apps based on Chromium sources and allow to opt-in in extension's options.

**Comment by gregolsky** [comment]
Duplicate of #31
