### ISSUE TITLE
Make App Name Less Generic

### ISSUE THREAD

**Issue by UltimateZedJones** [gregolsky/chrome-app-launcher#69]
I'd like to promote the app and use it as a default on my student's terminals, however, when recommending it to others, many are confused by the generic name which is used by other apps in the Chrome Web Store. 

Please re-brand. Even "Lachowski App Launcher for Chrome" is more preferable (and what I've been using to explain which one to install).

I didn't want to submit this as an "issue" but there appears to be no contact option within the app.

Thank you for taking the time to read some random internet guy's opinion on your app.

-Zed

**Comment by gregolsky** [comment]
Sorry, I cannot do that due to Chrome Webstore restrictions.
