### ISSUE TITLE
Dragging disabled

### ISSUE THREAD

**Issue by TerenceH** [gregolsky/chrome-app-launcher#70]
Hello, 
Suddenly I am unable to rearrange icons like I used to. I don't know since when but I discovered it yesterday. I also updated to Chrome Version 62.0.3202.62 (Official Build) (64-bit) yesterday but now I don't remember if that was after or before I started noticing. As far as I can remember it worked fine in the previous Chrome build.

**Comment by gregolsky** [comment]
Hi,

I just update to 62 and I am experiencing the same thing. I'll take a look
into it in the evening.
Thanks for reporting that!

czw., 19 paź 2017 o 14:28 użytkownik Terence Hoefdraad <
notifications@github.com> napisał:

**Comment by TerenceH** [comment]
Ok, great! Thank you!

**Comment by gregolsky** [comment]
Fixed in 2.4.11. Should be available in an hour or so.

**Comment by gregolsky** [comment]
Note: you can force update extensions by going to chrome://extensions/ and clicking *Update extensions now* button on top of the page.

**Comment by TerenceH** [comment]
It's fixed now. Awesome! 
 
> Note: you can force update extensions by going to chrome://extensions/ and clicking Update extensions now button on top of the page.

You should add: tick the _Developer mode_ option on top of the page to reveal the _Update extensions now_ button
