### ISSUE TITLE
Shortcut override of Google Docs (Extension)

### ISSUE THREAD

**Issue by tvarano54** [gregolsky/chrome-app-launcher#72]
When using Google docs, a common shortcut is ctrl + space to format to superscript. However, when having the Chrome Apps extension on my browser (chrome), it opens using the same function, providing an unwanted dropdown. Is there a way to remove the shortcut (I might just not be aware)?

**Comment by godey4me** [comment]
Yes, you can change the shortcut to whatever key combination you want. I have mine set to Alt+E.

Go to chrome=>overflow menu (3dots on right of navigation bar) =>more tools=>extensions. Scroll to the bottom to find keyboard shortcuts. Look for apps Launcher and set your desired key combination.

Note: On Chrome 65 and above (I think) the keyboard shortcuts have been moved to the left side menu.

**Comment by gregolsky** [comment]
Thanks godey4me. Closing, since you solved the issue.

**Comment by rivR789** [comment]
@godey4me literally. i. love. you.
thank you so much
